version: '3.9'
services:
  apish:
    image: draftable/apish
    ports:
      # HTTP
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      # HTTPS
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - draftable-apish:/srv/draftable
      - /sys/fs/cgroup:/sys/fs/cgroup
volumes:
  draftable-apish:
